fix general yml

diff --git a/.github/workflows/general.yml b/.github/workflows/general.yml
--- a/.github/workflows/general.yml
+++ b/.github/workflows/general.yml
@@ -54,8 +54,9 @@ jobs:
           fi
 
           sshpass -p "${{ secrets[ matrix.server.secret ] }}" rsync -avz --delete --exclude='.env*' \
+            --no-perms --no-owner --no-group \
             -e "ssh -o StrictHostKeyChecking=no" \
-            ./ $USER@${{ matrix.server.host }}:/var/www/fe-cms-gwt/
+            ./ $USER@${{ matrix.server.host }}:/var/www/fe-cms-gwt/ || echo "Rsync failed on ${{ matrix.server.name }}"
 
       - name: Restart on ${{ matrix.server.name }}
         run: |
@@ -67,5 +68,5 @@ jobs:
 
           sshpass -p "${{ secrets[ matrix.server.secret ] }}" ssh -o StrictHostKeyChecking=no $USER@${{ matrix.server.host }} << 'EOF'
             systemctl restart nginx
-            pm2 restart fe-cms-gwt
+            pm2 restart fe-cms-gwt || pm2 start ecosystem.config.js --name fe-cms-gwt
           EOF
